spring:
  config:
    name: prod
#注册的地址
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15 #服务过期时间配置
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置
    hostname: bootadmin
  client:
    serviceUrl:
      defaultZone:  http://admin:admin**123@eureka1:8761/eureka,http://admin:admin**123@eureka2:8761/eureka
#公开了prometheus,health,info,logfile
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: ${user.home}/logs/bootadmin-info.log
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        # 避免访问 zipkin 页面报 java.lang.IllegalArgumentException
        auto-time-requests: false
    tags:
      application: ${spring.application.name}
      hikaricp: ${spring.datasource.poolName}
      instance: ${spring.application.name}-${spring.cloud.client.ip-address}