spring:
  config:
    name: local
#端口
server:
  port: 8999
#注册的地址
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15 #服务过期时间配置
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5 #client刷新本地缓存时间
#公开了prometheus,health,info,logfile
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: ${user.home}/logs/zipkin-info.log
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        # 避免访问 zipkin 页面报 java.lang.IllegalArgumentException
        auto-time-requests: false
    tags:
      application: ${spring.application.name}
      hikaricp: ${spring.datasource.poolName}
      instance: ${spring.application.name}-${spring.cloud.client.ip-address}